version: '3'
services:
  iris:
    env_file: .env
    image: intersystemsdc/irishealth-community
    ports:
      - 8772:1972
      - 8773:52773
    working_dir: /home/irisowner/zprofile/
    volumes:
     - ./init.db:/docker-entrypoint-initdb.d/
     - ./:/home/irisowner/zprofile/
     - emptyweb:/home/irisowner/zprofile/web
     - ./web:/usr/irissys/csp/zprofile/
volumes:
  emptyweb: